### ISSUE TITLE
Journal 3

### ISSUE THREAD

**Issue by fazilothman** [RazerMS/OpenCart3.0_Plugin#1]
How to intergrate with journal 3 quick checkout?

**Comment by apis17** [comment]
Hi @fazilothman , currently not have journal3 quick checkout integration.

**Comment by fazilothman** [comment]
Thanks. bit different from journal2 that been shared before. Hope Molpay team make for this one too.

**Comment by apis17** [comment]
please send request to support@molpay.com to assist you better.
